export {
  createFileRoute,
  Link,
  useSearch,
  useParams,
  useNavigate,
  useLocation,
  createRootRouteWithContext,
  createRootRoute,
  createRouter,
  HeadContent,
  Scripts,
  Outlet,
  useRouter,
  useRouteContext,
} from '@tanstack/react-router';
